# Generated by Django 4.1.5 on 2023-01-09 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New picture', max_length=255)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='UserPictureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favourites', models.BooleanField(default=False)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='picture.picture')),
            ],
        ),
    ]
